name: Python CI + Build + Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: run tests
        run: |
          export PYTHONPATH='${{ github.workspace }}'
          pytest

  build:
    name: Build Python Package
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install build tools
        run: pip install build

      - name: build project
        run: python -m build

      - name: Show artifacts
        run: ls -lh dist

  docker:
    name: build docker image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t quote-btc .

      - name: test contianer
        run: docker run --rm quote-btc